### PR TITLE
feat(semantic-release): implement for this formula

### LINKED ISSUE #1: Finalise `semantic-release` process
https://github.com/n-rodriguez/telegraf-formula/issues/1

### PR DESCRIPTION
**Pull request by myii**
* Transferred from https://github.com/n-rodriguez/telegraf-formula/pull/2

---

* Automated using https://github.com/myii/ssf-formula/pull/55
* Close #1
* Fix `yamllint` errors:

```bash
telegraf-formula$ yamllint -s .
./telegraf/osfamilymap.yaml
  35:89     error    line too long (102 > 88 characters)  (line-length)

./telegraf/osfingermap.yaml
  14:2      error    syntax error: found character '%' that cannot start any token
  75:89     error    line too long (117 > 88 characters)  (line-length)
```

---

This is working on all instances except for `amazonlinux-2` and `arch-base-latest`:

* https://travis-ci.org/myii/telegraf-formula/builds/592768977
* https://travis-ci.org/myii/telegraf-formula/builds/592791086

To get this working on Arch, the following references are helpful:

* https://wiki.archlinux.org/index.php/Telegraf
* https://aur.archlinux.org/packages/telegraf/
  - This would require `git.latest`
  - Start from https://github.com/saltstack-formulas/iscsi-formula/blob/aa5a94555a46b81ffa2d4efe579deaf0ce0c965b/iscsi/osfamilymap.yaml#L70
* https://www.archlinux.org/packages/?sort=&q=pytoml&maintainer=&flagged=
  - This is already working

### CODE REVIEW

**Comment by n-rodriguez** [comment]
@myii  Why a `0.2.16` release?

**Comment by myii** [comment]
@n-rodriguez I "counted" the version numbers from the existing commit messages!  What would you calculate it as?  In any case, this will get bumped to `v0.3.0`.

**Comment by myii** [comment]
One problem is that the repo settings in Travis are inaccessible, so there's no way of knowing whether the GitHub token is in place automatically.  So the release may not get triggered.  If that happens, I'll make a request on Slack for this to be fixed.

**Comment by n-rodriguez** [comment]
> @n-rodriguez I "counted" the version numbers from the existing commit messages! What would you calculate it as? In any case, this will get bumped to `v0.3.0`.

Ok fine!

**Comment by n-rodriguez** [comment]
> One problem is that the repo settings in Travis are inaccessible, so there's no way of knowing whether the GitHub token is in place automatically. So the release may not get triggered. If that happens, I'll make a request on Slack for this to be fixed.

Ok. So merge it and try!

**Comment by myii** [comment]
@n-rodriguez I was leaving it for you to merge (so that I could blame you when it didn't work!).  Seriously though, I just wanted to make sure everything was good from your side before proceeding.  Thanks for the review.

**Comment by n-rodriguez** [comment]
@myii thanks for your help!

**Comment by myii** [comment]
@n-rodriguez You're welcome.  It _didn't_ work the first time but for some reason, Travis let me in to the settings (seems to take a few minutes to get a new repo configured?), so I was able to get the GitHub token in.  Thanks for getting this formula started!

**Pull request merged**
